### ISSUE TITLE
Panic occurs when generating tables with only AUTO INCREMENT column

### ISSUE THREAD

**Issue by nao1215** [shogo82148/myddlmaker#67]
## Description / Steps to reproduce
When attempting to create an SQL file from the structure shown below, a panic occurs and SQL generation fails.
```go
package schema

import (
	"github.com/shogo82148/myddlmaker"
)

type Sample struct {
	ID uint64 `ddl:",auto"`
}

func (*Sample) PrimaryKey() *myddlmaker.PrimaryKey {
	return myddlmaker.NewPrimaryKey("id")
}
```

```shell
➜   go generate ./...
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/shogo82148/myddlmaker.(*Maker).generateGoTableInsert(0x0?, {0x104584b28, 0x140000767b0}, 0x1400010ce40)
        /Users/naohirochikamatsu/go/pkg/mod/github.com/shogo82148/myddlmaker@v0.0.8/maker.go:457 +0x6a8
github.com/shogo82148/myddlmaker.(*Maker).generateGoTable(0x1400002e0c0?, {0x104584b28, 0x140000767b0}, 0xd?)
        /Users/naohirochikamatsu/go/pkg/mod/github.com/shogo82148/myddlmaker@v0.0.8/maker.go:431 +0x2c
github.com/shogo82148/myddlmaker.(*Maker).GenerateGo(0x1400002e0c0, {0x104584b48, 0x14000054038})
        /Users/naohirochikamatsu/go/pkg/mod/github.com/shogo82148/myddlmaker@v0.0.8/maker.go:396 +0x98
github.com/shogo82148/myddlmaker.(*Maker).GenerateGoFile(0x1400002e0c0)
        /Users/naohirochikamatsu/go/pkg/mod/github.com/shogo82148/myddlmaker@v0.0.8/maker.go:381 +0x110
github.com/template_webapi/app/datastore/schema.GenerateDDL()
        /Users/naohirochikamatsu/ghq/github.com/webapi/app/datastore/schema/schema.go:46 +0x1bc
main.main()
        /Users/naohirochikamatsu/ghq/github.com/webapi/app/datastore/schema/gen/main.go:6 +0x1c
exit status 2
schema.go:7: running "go": exit status 1
```

If the auto tag is removed, no panic will occur. 

## Expected behavior
The myddlmaker print good error message that is easy to speculate about the cause of panic.

**Comment by shogo82148** [comment]
closed by #68
